# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    paths:
    - 'src/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'src/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # https://github.com/marketplace/actions/deploy-to-github-pages
    - name: Checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: false
    - name: Build with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci --prefix src
    - run: npm run build --if-present --prefix src
    - run: npm test --prefix src
    - run: npm run generate --prefix src
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: src/dist # The folder the action should deploy.
        TARGET_FOLDER: docs # The folder where the content should be deployed
        CLEAN: true # Automatically remove deleted files from the deploy branch
        GIT_CONFIG_NAME: Github Pages
        GIT_CONFIG_EMAIL: noreply@github.com